### ISSUE TITLE
We need to have - more controls 

### ISSUE THREAD

**Issue by nmondal** [abhishekshah1998/CoinToss#2]
1. For increasing /decreasing pressure 
2. Increasing decreasing drag

**Comment by abhishekshah1998** [comment]
Okay Sir. I have been measuring the pressure using the getPressure() method on touch activity.

I understand that having a drag and scale widget would be better for most of the android devices. I will add this in the next update.

**Comment by nmondal** [comment]
Ok. So the following goes in then:

Trigger where you are applying the pressure to toss ( Tap to toss ) with a pressure control 
Coins of various countries coming in 
Change the background.

**Comment by abhishekshah1998** [comment]
1. I have added a seekbar to control the force.
2. I have added a coin of US. Will add more on approval.
3. Added 2 different backgrounds. Still searching for an ideal background.

**Comment by nmondal** [comment]
Are we done here? Is this working now all good an well?

**Comment by abhishekshah1998** [comment]
Yes Sir, there as no bugs as such. I have even added a control for the distance from the center as per the diagram provided by you.
![image](https://user-images.githubusercontent.com/23608784/85860415-672e5800-b7dc-11ea-85e8-5ef1195e6677.png)
I'll keep finding a better background for a better UX.
Should I close this issue?

**Comment by nmondal** [comment]
We are good.
